name: Docker Build and Push

on:
  push:
    branches: [main]
    paths:
      - "back-end/**"
  pull_request:
    branches: [main]
    paths:
      - "back-end/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./back-end
          file: ./back-end/Dockerfile
          platforms: linux/amd64
          push: true
          tags: merszerodev1023/fitness-go-backend:latest
          build-args: |
            SUPABASE_HOST=${{ secrets.SUPABASE_HOST }}
            SUPABASE_USER=${{ secrets.SUPABASE_USER }}
            SUPABASE_PASSWORD=${{ secrets.SUPABASE_PASSWORD }}
            SUPABASE_DBNAME=${{ secrets.SUPABASE_DBNAME }}
            SUPABASE_PORT=${{ secrets.SUPABASE_PORT }}
            SUPABASE_ID=${{ secrets.SUPABASE_ID }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_EXAMPLES_APPS_TOKEN }}"

      - name: Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: fitness-go-backend
          service-ports: "3000:http"
          service-routes: "/:3000"
          docker: merszerodev1023/fitness-go-backend:latest
          privileged: true
          service-env: |
            SUPABASE_HOST=${{ secrets.SUPABASE_HOST }}
            SUPABASE_USER=${{ secrets.SUPABASE_USER }}
            SUPABASE_PASSWORD=${{ secrets.SUPABASE_PASSWORD }}
            SUPABASE_DBNAME=${{ secrets.SUPABASE_DBNAME }}
            SUPABASE_PORT=${{ secrets.SUPABASE_PORT }}
            SUPABASE_ID=${{ secrets.SUPABASE_ID }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}`

      - name: Clean up Koyeb Service
        uses: koyeb/action-git-deploy/cleanup@v1
